apiVersion: v1
kind: Service
metadata:
  labels:
    app: identityservice
  name: identityservice
spec:
  ports:
    - protocol: "TCP"
      port: 5007
      targetPort: 80
      name: http
  selector:
    app: identityservice
status:
  loadBalancer: {}
