apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileupload
spec:
  replicas: 1
  selector:
    matchLabels:
        app: fileupload
  strategy: {}
  template:
    metadata:
        labels:
            app: fileupload
    spec:
      containers:
        - image: joobsterr/rocketcomimages
          name: fileuploadservice
          imagePullPolicy: Always
          ports:
            - containerPort: 80           
          resources: 
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
      restartPolicy: Always
status: {}
